version: "3.8"

services:
  nginx:
    image: nginx:latest
    build: ./nginx
    container_name: nginx_cont
    ports:
      - "80:80"
    depends_on:
      django_app:
        condition: service_healthy
    restart: always
    networks:
      - notes-app-nw

  django_app:
    image: surajmanjhi/my-note-app:latest
    container_name: django_cont
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw

  db:
    image: mysql:8.0
    container_name: db_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-nw

volumes:
  mysql_data:

networks:
  notes-app-nw:
