version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notes-app-nw

  django_app:
    image: surajmanjhi/my-note-app:latest
    container_name: django_cont
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    restart: always
    networks:
      - notes-app-nw

  nginx:
    image: nginx:latest
    container_name: nginx_cont
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django_app
    restart: always
    networks:
      - notes-app-nw

networks:
  notes-app-nw:
